const responses=[
 {keys:['order','track','where'],title:'Order Status',text:'I can help you track your order. For this demo, order <b>SO-2026-1042</b> is <b>Shipped</b> and is currently with the delivery partner.',next:'Next step: Check the tracking page using your order ID. If the package has not moved for 48 hours, choose Human Support.'},
 {keys:['delay','late','not arrived','delivery'],title:'Delivery Delay',text:'Sorry for the delay. Please check the latest tracking update first. Delivery times can change because of logistics or weather conditions.',next:'Next step: Keep your order ID ready. If the promised delivery date has passed, contact Human Support for an investigation.'},
 {keys:['return','exchange'],title:'Return Request',text:'You can request a return for an eligible item. Keep your order ID and select the reason for return. The item may need to meet the applicable return conditions.',next:'Next step: Start the return request and follow the pickup instructions shown by the seller.'},
 {keys:['refund','money back','refund status'],title:'Refund Status',text:'If your refund has been approved, the amount is normally processed back through the original payment method. Timing can vary by payment provider.',next:'Next step: If the expected refund period has passed, contact Human Support with your order or transaction reference.'},
 {keys:['cancel','cancellation'],title:'Cancel Order',text:'If your order has not been dispatched, cancellation may be possible. Once dispatched, you may need to use the return process instead.',next:'Next step: Provide your order ID and check whether the order is still eligible for cancellation.'},
 {keys:['product','price','available','specification','details'],title:'Product Enquiry',text:'I can help with basic product information. For accurate details such as current price, stock, size, warranty, or specifications, check the product page or seller information.',next:'Next step: Share the product name or ID. Do not enter card details or passwords.'},
 {keys:['payment','failed','transaction'],title:'Payment Support',text:'If a payment failed, verify your payment details and try again. If money was deducted, avoid repeating the payment until the transaction status is clear.',next:'Next step: Keep the transaction reference ready and contact Human Support if the status does not update.'}
];
const input=document.getElementById('queryInput'), area=document.getElementById('responseArea'), next=document.getElementById('nextStep');
function classify(q){q=q.toLowerCase();return responses.find(r=>r.keys.some(k=>q.includes(k)))}
function answer(q){if(!q.trim())return showToast('Please enter a question.');const r=classify(q);area.innerHTML=r?'<div class="eyebrow">QUERY IDENTIFIED</div><h4>'+r.title+'</h4><p style="color:#c7c8cd;font-size:13px;line-height:1.7">'+r.text+'</p>':'<div class="empty-icon">?</div><h4>We need a little more information</h4><p>I could not confidently identify your request. Try Order Status, Return, Refund, Cancellation, Delivery Delay, or Product Enquiry.</p>';next.classList.remove('hidden');next.innerHTML=r?'<b>Next step:</b> '+r.next.replace('Next step: ',''):'<b>Next step:</b> Please rephrase your question or use Human Support for help.'}
document.getElementById('sendBtn').onclick=()=>answer(input.value);input.addEventListener('keydown',e=>{if(e.key==='Enter')answer(input.value)});document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;answer(input.value);document.getElementById('support').scrollIntoView({behavior:'smooth'})});
function quickReply(q){const c=document.getElementById('miniChat');c.insertAdjacentHTML('beforeend','<div class="msg user">'+q+'</div>');const r=classify(q);c.insertAdjacentHTML('beforeend','<div class="msg bot">'+(r?r.text.replace(/<[^>]+>/g,''):'Please choose a support category below for more help.')+'</div>')}
function openHumanSupport(){document.getElementById('supportModal').classList.remove('hidden')}function closeHumanSupport(){document.getElementById('supportModal').classList.add('hidden')}function submitSupport(){closeHumanSupport();showToast('Demo support request created. A human agent would follow up.')}function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}